# -*- coding: utf-8 -*-
"""Dark.Web.Detectives-POS-ITT103-SP2026.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHx9o-M-j2OeHRI0FZK0Szpe7JEvVeCz
"""

# --- Part A: Predefined Product Inventory List ---
inventory = [
    {"product": "Water", "type": "Beverages", "quantity": 1000, "price": 100},
    {"product": "Soft Drink", "type": "Beverages", "quantity": 570, "price": 150},
    {"product": "Soda", "type": "Beverages", "quantity": 600, "price": 190},
    {"product": "Rice", "type": "Groceries", "quantity": 89, "price": 250},
    {"product": "Flour", "type": "Groceries", "quantity": 189, "price": 200},
    {"product": "Spaghetti", "type": "Groceries", "quantity": 23, "price": 850},
    {"product": "Bleach", "type": "Househ-items", "quantity": 230, "price": 280},
    {"product": "Powdered Soap", "type": "Househ-items", "quantity": 50, "price": 500},
    {"product": "Detergent", "type": "Househ-items", "quantity": 80, "price": 350},
    {"product": "Icecream", "type": "Dairy", "quantity": 359, "price": 670},
]

# --- Part B: Shopping Cart Operations ---
cart = [] # This will store dictionaries of bought items

#Display Inventory
def show_inventory():
    print("\n--- STORE INVENTORY ---")
    for i in range(len(inventory)):
        item = inventory[i]
        print(f"{i+1}. {item['product']} - ${item['price']} (Stock: {item['quantity']})")

#Used to validate stock before adding to cart.
def check_low_stock():
    print("\n--- STOCK ALERTS ---")
    found_low = False
    for item in inventory:
        if item['quantity'] < 5:
            print(f"ALERT: {item['product']} is critically low!")
            found_low = True
    if not found_low:
        print("All stock levels are okay.")

#Main Program

#Menu Display to accept user input
def start_pos():
    while True:
        print("\n1. Add Item  2. Remove Item  3. View Cart  4. Checkout  5. Exit")
        choice = input("Select an option: ")

#Add items to cart
        if choice == "1":
            show_inventory()
            try:
                idx = int(input("Enter item number to add: ")) - 1
                qty = int(input("Enter quantity: "))

                selected_item = inventory[idx]

                if qty <= selected_item['quantity']:
                    # Create a dictionary for the cart entry
                    cart_entry = {
                        "name": selected_item['product'],
                        "price": selected_item['price'],
                        "qty": qty
                    }
                    cart.append(cart_entry)
                    # Reduce stock in inventory
                    selected_item['quantity'] -= qty
                    print(f"Added {qty} {selected_item['product']} to cart.")
                else:
                    print("Error: Not enough stock!")
            except:
                print("Invalid selection.")

#Remove items from cart.
        elif choice == "2":
            if not cart:
                print("Cart is empty.")
            else:
                for i in range(len(cart)):
                    print(f"{i+1}. {cart[i]['name']}")
                rem_idx = int(input("Enter number to remove: ")) - 1
                removed = cart.pop(rem_idx)
                # Return stock to inventory
                for item in inventory:
                    if item['product'] == removed['name']:
                        item['quantity'] += removed['qty']
                print("Item removed.")
#View Cart
        elif choice == "3":
            print("\n--- YOUR CART ---")
            total = 0
            for item in cart:
                item_total = item['price'] * item['qty']
                print(f"{item['name']} x{item['qty']}: ${item_total}")
                total += item_total
            print(f"Subtotal: ${total}")
# Check Out
        elif choice == "4":
            if not cart:
                print("Add items before checkout!")
                continue

            subtotal = 0
            for item in cart:
                subtotal += item['price'] * item['qty']

            # 5% Discount over $5000
            discount = 0
            if subtotal > 5000:
                discount = subtotal * 0.05

            tax = (subtotal - discount) * 0.10
            total_due = (subtotal - discount) + tax

            print(f"\nTOTAL DUE (Inc. Tax): ${total_due:.2f}")
            payment = float(input("Enter cash received: "))

            if payment >= total_due:
                # --- PRINT RECEIPT ---
                print("\n" + "="*30)
                print("      BEST BUY RETAIL      ")
                print("="*30)
                for item in cart:
                    print(f"{item['name']} x{item['qty']} @ ${item['price']}")
                print("-" * 30)
                print(f"Subtotal:  ${subtotal:.2f}")
                print(f"Discount: -${discount:.2f}")
                print(f"Tax:      ${tax:.2f}")
                print(f"TOTAL:    ${total_due:.2f}")
                print(f"Change:   ${payment - total_due:.2f}")
                print("="*30)
                print("   THANK YOU FOR SHOPPING! ")

                check_low_stock()
                cart.clear() # This makes it reset for next customer
                break
            else:
                print("Insufficient funds!")

        elif choice == "5":
            break

start_pos()

